<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.17763.0</TargetFramework>
		<SupportedOSPlatformVersion>10.0.17763.0</SupportedOSPlatformVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>logo.ico</ApplicationIcon>
		<Version>1.0.5</Version>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="logo.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="HtmlAgilityPack" Version="1.12.4" />
		<PackageReference Include="Microsoft.Playwright" Version="1.58.0" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3800.47" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
		<PackageReference Include="QuestPDF" Version="2026.2.3" />
		<PackageReference Include="Sentry" Version="6.2.0" />
	</ItemGroup>

</Project>